-- Copyright (C) 2020  Intel Corporation. All rights reserved.
-- Your use of Intel Corporation's design tools, logic functions 
-- and other software and tools, and any partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Intel Program License 
-- Subscription Agreement, the Intel Quartus Prime License Agreement,
-- the Intel FPGA IP License Agreement, or other applicable license
-- agreement, including, without limitation, that your use is for
-- the sole purpose of programming logic devices manufactured by
-- Intel and sold by Intel or its authorized distributors.  Please
-- refer to the applicable agreement for further details, at
-- https://fpgasoftware.intel.com/eula.

-- Generated by Quartus Prime Version 20.1.0 Build 711 06/05/2020 SJ Lite Edition
-- Created on Wed Oct 02 18:35:01 2024

LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY state IS
    PORT (
        reset : IN STD_LOGIC := '0';
        clock : IN STD_LOGIC;
        x : IN STD_LOGIC := '0';
        z : OUT STD_LOGIC;
        z2 : OUT STD_LOGIC;
        z3 : OUT STD_LOGIC
    );
END state;

ARCHITECTURE BEHAVIOR OF state IS
    TYPE type_fstate IS (state1,state2,state3);
    SIGNAL fstate : type_fstate;
    SIGNAL reg_fstate : type_fstate;
    SIGNAL reg_z : STD_LOGIC := '0';
    SIGNAL reg_z2 : STD_LOGIC := '0';
    SIGNAL reg_z3 : STD_LOGIC := '0';
BEGIN
    PROCESS (clock,reg_fstate,reg_z,reg_z2,reg_z3)
    BEGIN
        IF (clock='1' AND clock'event) THEN
            fstate <= reg_fstate;
            z <= reg_z;
            z2 <= reg_z2;
            z3 <= reg_z3;
        END IF;
    END PROCESS;

    PROCESS (fstate,reset,x)
    BEGIN
        IF (reset='1') THEN
            reg_fstate <= state1;
            reg_z <= '0';
            reg_z2 <= '0';
            reg_z3 <= '0';
        ELSE
            reg_z <= '0';
            reg_z2 <= '0';
            reg_z3 <= '0';
            CASE fstate IS
                WHEN state1 =>
                    IF ((x = '1')) THEN
                        reg_fstate <= state2;
                    ELSIF (NOT((x = '1'))) THEN
                        reg_fstate <= state1;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= state1;
                    END IF;

                    reg_z <= '1';

                    reg_z3 <= '0';

                    reg_z2 <= '0';
                WHEN state2 =>
                    IF ((x = '1')) THEN
                        reg_fstate <= state3;
                    ELSIF (NOT((x = '1'))) THEN
                        reg_fstate <= state2;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= state2;
                    END IF;

                    reg_z <= '0';

                    reg_z3 <= '0';

                    reg_z2 <= '1';
                WHEN state3 =>
                    IF ((x = '1')) THEN
                        reg_fstate <= state1;
                    ELSIF (NOT((x = '1'))) THEN
                        reg_fstate <= state3;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= state3;
                    END IF;

                    reg_z <= '0';
                    reg_z <= '1';

                    reg_z2 <= '0';
                WHEN OTHERS => 
                    reg_z <= 'X';
                    reg_z2 <= 'X';
                    reg_z3 <= 'X';
                    report "Reach undefined state";
            END CASE;
        END IF;
    END PROCESS;
END BEHAVIOR;
